name: manual Test workflow

on:
  push:
    branches:["main"]
    
  workflow_dispatch:
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
    - name: Display simple message
      run: echo "Hello this workflow is working"
    
  test:
    runs-on: ubuntu-latest
    steps:
    - name: another test action
      run: echo "this is Test job"
      
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy test app in azure vm
      run: echo "deployment about to start"
    - name: deploy app in azure
      uses: ilCollez/ssh-scp-deploy@main
       with: 
          host: ${{ secrets.SSH_HOST }} # "example.com"
          port: ${{ secrets.SSH_PORT }} # 22
          username: ${{ secrets.SSH_USER }} # "user"
          key: ${{ secrets.SSH_KEY }} # "~/.ssh/id_rsa", can also be the key itself
  #  passphrase: ${{ secrets.SSH_PASSPHRASE }} # "passphrase"
          files: |
              index.html
          remote-path: "/var/www/html"
          clean: true
          before-upload: |
            echo "Executed before upload"

          pm2 stop service
          after-upload: |
             echo "Executed after upload"

              npm ci --production
              npm run build
              npm test
