name: manual Test workflow

on:
  push:
    branches:
        - main
    
  workflow_dispatch:
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
    - name: Display simple message
      run: echo "Hello this workflow is working"
    
  test:
    runs-on: ubuntu-latest
    steps:
    - name: another test action
      run: echo "this is Test job"
      
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Code
      uses: actions/checkout@v3
    
    - name: Present Working Directory
      run:  pwd
    
    - name: Copy the index.html to ubunto server
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: 'index.html'
        remote: '~/index.html'
        host: ${{secrets.HOST}}
        user: ${{secrets.USER}}
        key: ${{secrets.key}}
        pre_upload: sudo rm -rf /var/www/html/index.html
        post_upload: sudo mv ~/index.html /var/www/html/index.html
        ssh_options: -o StrictHostKeyChecking=no
